# Generated by Django 5.2.4 on 2025-07-11 13:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='programstudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('kode', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('mahasiswa', 'Mahasiswa'), ('dosen', 'Dosen')], default='mahasiswa', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Kursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('dosen', models.ForeignKey(limit_choices_to={'role': 'dosen'}, on_delete=django.db.models.deletion.CASCADE, related_name='kursus_dosen', to=settings.AUTH_USER_MODEL)),
                ('mahasiswa_terdaftar', models.ManyToManyField(blank=True, related_name='kursus_mahasiswa', to=settings.AUTH_USER_MODEL)),
                ('program_studi', models.ForeignKey(blank=True, limit_choices_to={'role': 'mahasiswa'}, on_delete=django.db.models.deletion.CASCADE, related_name='kursus_terdaftar', to='core.programstudi')),
            ],
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('urutan', models.PositiveIntegerField()),
                ('kursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modul', to='core.kursus')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('konten', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='materi_files/')),
                ('urutan', models.PositiveIntegerField()),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi', to='core.modul')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='ProgressBelajar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selesai', models.BooleanField(default=False)),
                ('tanggal_selesai', models.DateTimeField(blank=True, null=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materi')),
            ],
            options={
                'unique_together': {('mahasiswa', 'materi')},
            },
        ),
    ]
