# Generated by Django 5.2.4 on 2025-07-22 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kursus',
            name='program_studi',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='kursus_terdaftar', to='core.programstudi'),
        ),
    ]
